### PR TITLE
Make TranslationKeyExists also check section translations

### LINKED ISSUE #473: TranslationKeyExists doesn't check section translations
If i have a section with translations, it will send this error: `"submit" does not have a matching entry in 'locales/en.default.json'.`

```liquid
{{ 'submit' | t }}
```

```json
{
  ...
  "locales": {
    "en": {
      "submit": "Subscribe"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by hannakebedom**
Made the TranslationKeyExists check also look for translation keys in the section schema tag. Resolves #473

### CODE REVIEW

File: test/checks/translation_key_exists_test.rb [hunk 1]
```diff
@@ -39,6 +39,38 @@ def test_ignores_existing_key
...
+        {% schema %}
+          {
+            "locales": {
+              "en": {
+                "submit": "Subscribe"
+              }
+            }
+          }
+        {% endschema %}
+        {{"submit" | t}}
```
Comment (charlespwd) [inline test/checks/translation_key_exists_test.rb:55]: The schema is usually at the bottom of a file. Not the top. I believe this breaks if we flip the order.

File: lib/theme_check/checks/translation_key_exists.rb [hunk 2]
```diff
@@ -5,16 +5,41 @@ class TranslationKeyExists < LiquidCheck
...
+          key_exists?(key_node.value, @theme.default_locale_json.content) || ShopifyLiquid::SystemTranslations.include?(key_node.value),
           "'#{key_node.value}' does not have a matching entry in '#{@theme.default_locale_json.relative_path}'",
+          node,
+          key_node
+        )
+      end
+    end
+
+    def add_as_offense(boolean, message, node, key_node)
+      unless boolean
```
Comment (charlespwd) [inline lib/theme_check/checks/translation_key_exists.rb:40]: I don't think this works. We might traverse the node before the schema is defined. (See comment about unit test below).

I believe the right way to do this would be to collect the translation nodes as we're traversing the document.

Something like 
```
def on_variable(node)
  if ...
  if ...
  @nodes << node
end

def on_end
  @nodes.each do |node|
    unless (key_node = node...)
    unless translation_exists?(key_node.value)
    add_as_offense(
      "'#{key_node.value'" not found in #{search_path}"
    )
  end

  def translation_exists?(key)
    key_exists?(key, @theme...) ||
    key_exists?(key, @schema_locales) ||
    SystemTranslations.include?(key)
  end
end
```

Also, I think we could clean that up a bit. If we do `@schema_locales = {}`, then we can call `key_exists?(..., @schema_locales)` even when there wasn't a schema in the page. And I believe this would simplify a lot of the logic.

**Review by charlespwd — CHANGES_REQUESTED** [review]

File: lib/theme_check/checks/translation_key_exists.rb [hunk 3]
```diff
@@ -5,18 +5,31 @@ class TranslationKeyExists < LiquidCheck
     category :translation
     doc docs_url(__FILE__)
 
+    def initialize
+      @schema_locales = {}
+      @nodes = []
```
Comment (charlespwd) [inline lib/theme_check/checks/translation_key_exists.rb:10]: Just remembered that Check instances are reused between files. Might want to do something like UnusedAssign and have nodes per file.

```
def initialize
  @nodes = {}
end

def on_document(node)
  @nodes[node.theme_file.name] = []
end

def on_variable(node)
  #...
  @nodes[node.theme_file.name] << node
end

# etc.
```

**Review by charlespwd — CHANGES_REQUESTED** [review]

File: lib/theme_check/checks/translation_key_exists.rb (hunk 3 above)
Comment (charlespwd) [reply lib/theme_check/checks/translation_key_exists.rb:10]: Otherwise the @nodes array will keep growing as more files are checked.

Comment (hannakebedom) [reply lib/theme_check/checks/translation_key_exists.rb:10]: Yea, this makes sense.

**Review by DrTeePot — COMMENTED** [review]
Almost there!

**Review by charlespwd — APPROVED** [review]
LGTM
