### PR TITLE
Fix document links from different root

### LINKED ISSUE #231: Snippet Document Links don't account for root config
I was super psyched for this update. I was actually planning on creating an extension to do exactly this.

Regrettably, there seems to be a small issue where it doesn't account for the `root` config setting, meaning the snippets directory is incorrect.

`root: src/theme`

image
Censored part is the Project Root directory.

### PR DESCRIPTION
**Pull request by charlespwd**
Fixes #231

Had to refactor a little bit here. Made it clearer that the expected API for read/write on Storage is relative_paths. Also made it so the handler was properly using relative paths when calling the completion and document link engines.

Also:
- Added integration tests for document link (with/without root attribute)
- Refactored all the storage.root.join(...).to_s -> storage.path(...) in tests
- Also made the urls in diagnostics use `file://` instead of `file:`. Since I believe `file://` is the standard. (I'm being redirected in a browser anyway.)

### CODE REVIEW

**Comment by charlespwd** [comment]
Dat flaky test 😡 :fire:

**Comment by charlespwd** [comment]
Flaky test fixed in #238

File: lib/theme_check/file_system_storage.rb [hunk 1]
```diff
@@ -12,7 +12,7 @@ def initialize(root, ignored_patterns: [])
     end
 
     def path(relative_path)
-      @root.join(relative_path)
```
Comment (macournoyer) [inline lib/theme_check/file_system_storage.rb:15]: Is this really needed? Would prevent using any `Pathname` methods on this later.

**Review by macournoyer — APPROVED** [review]
LGTM!

File: lib/theme_check/file_system_storage.rb (hunk 1 above)
Comment (charlespwd) [reply lib/theme_check/file_system_storage.rb:15]: Actually I did it for consistency with the other one and because I was using + in the unit tests. I definitely can change both to paths!

**Comment by charlespwd** [comment]
Ooops fat finger. I'll add add my PR fixes in another PR.
