### PR TITLE
Fix VSCode problems not clearing problems when file is deleted

### LINKED ISSUE #136: Errors related to missing or unused files do not go away after correcting them
I was missing a file, so then I add it or I deleted an unused file, it is still showing up in the problems list though in the output tab for `theme-check` it shows the count going down for the errors as I delete the unused files:

```
Found 57 templates, and 32 offenses
Handler does not respond to on_text_document_did_close
Checking /Users/mac/src/github.com/Shopify/blah
Found 56 templates, and 31 offenses
Handler does not respond to on_text_document_did_close
Checking /Users/mac/src/github.com/Shopify/blah
Found 55 templates, and 30 offenses
Handler does not respond to on_text_document_did_close
Checking /Users/mac/src/github.com/Shopify/blah
Found 54 templates, and 29 offenses
Handler does not respond to on_text_document_did_close
Checking /Users/mac/src/github.com/Shopify/blah
Found 54 templates, and 29 offenses
...
```

image

Slack context from @charlespwd :

> CP Clermont:bulb:  3 days ago
> Similar bug as the other one. Would need to send empty diagnostics.
> 
> CP Clermont:bulb:  3 days ago
> We should open a GitHub issue for that
> 
> CP Clermont:bulb:  3 days ago
> (in theme-check, not theme-check-vscode)
> 
> CP Clermont:bulb:  3 days ago
> That's an [LSP](https://github.com/microsoft/language-server-protocol) bug

### PR DESCRIPTION
**Pull request by macournoyer**
Fixes #136 

Switch approach from reporting diagnostic for every templates currently on disk, to only reporting the ones reported previously.

Should report less diagnostics, and handle file deletion.

### CODE REVIEW

File: lib/theme_check/language_server/handler.rb [hunk 1]
```diff
@@ -42,27 +43,35 @@ def analyze_and_send_offenses(file_path)
...
-          contains_offenses.push(template.path)
+          reported_files << template.path
         end
 
-        # Publish diagnostics with empty array if template does not contain error
-        templates.select { |t| !contains_offenses.include?(t.path) }.each do |template|
-          send_diagnostic(template.path, [])
+        # Publish diagnostics with empty array if all issues on a previously reported template
+        # have been solved.
+        (@previously_reported_files - reported_files).each do |path|
```
Comment (charlespwd) [inline lib/theme_check/language_server/handler.rb:70]: TIL you can do subtraction on sets and it's pretty. I assume this means all the elements in previously reported that are not in reported?

**Review by charlespwd — APPROVED** [review]

File: lib/theme_check/language_server/handler.rb (hunk 1 above)
Comment (macournoyer) [reply lib/theme_check/language_server/handler.rb:70]: Correct!
